<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="G10GGNLT052" name="LEED v4.1 O+M: Existing Buildings" tests="69" failures="60" timestamp="20 Sep 2019 10:17:27 GMT" time="800.177" errors="0">
  <testcase name="LOAuthenticateAPI" time="2.017" classname="com.arcapi.Leedv4Testcases.LOAuthenticateAPITest"/>
  <testcase name="LEEDv4OMExistingBuildingsAPI" time="4.404" classname="com.arcapi.Leedv4Testcases.LEEDv4OMExistingBuildingsAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [403]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.LEEDv4OMExistingBuildingsAPITest.LEEDv4OMExistingBuildingsAPI(LEEDv4OMExistingBuildingsAPITest.java:29)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LEEDv4OMExistingBuildingsAPI -->
  <testcase name="LoginAPI" time="6.723" classname="com.arcapi.Common.LoginAPITest"/>
  <testcase name="LOProjectSyncAPI" time="3.589" classname="com.arcapi.Leedv4Testcases.LOProjectSyncAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.LOProjectSyncAPITest.LOProjectSyncAPI(LOProjectSyncAPITest.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LOProjectSyncAPI -->
  <testcase name="SignAgreementRegistrationAPI" time="2.328" classname="com.arcapi.Leedv4Testcases.SignAgreementRegistrationAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.SignAgreementRegistrationAPITest.SignAgreementRegistrationAPI(SignAgreementRegistrationAPITest.java:32)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SignAgreementRegistrationAPI -->
  <testcase name="AssetUpdateforNewAssetPUTAPI" time="1.946" classname="com.arcapi.Buildingtestcases.AssetUpdateBuildingAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Buildingtestcases.AssetUpdateBuildingAPITest.AssetUpdateforNewAssetPUTAPI(AssetUpdateBuildingAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetUpdateforNewAssetPUTAPI -->
  <testcase name="VerifyProjectRegisteredAssetList" time="2.469" classname="com.arcapi.Common.VerifyProjectRegisteredAssetListTest">
    <failure type="java.lang.AssertionError" message="List does not have LEED ID expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: List does not have LEED ID expected [true] but found [false]
	at com.arcapi.Common.VerifyProjectRegisteredAssetListTest.VerifyProjectRegisteredAssetList(VerifyProjectRegisteredAssetListTest.java:26)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- VerifyProjectRegisteredAssetList -->
  <testcase name="AssetDocumentAPI" time="2.006" classname="com.arcapi.Common.AssetDocumentAPITest"/>
  <testcase name="DownloadDocumentsAPI" time="1.664" classname="com.arcapi.Common.DownloadDocumentsAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.DownloadDocumentsAPITest.DownloadDocumentsAPI(DownloadDocumentsAPITest.java:29)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DownloadDocumentsAPI -->
  <testcase name="FetchingAgreementDetailsAPI" time="1.902" classname="com.arcapi.Common.FetchingAgreementDetailsAPITest"/>
  <testcase name="VerifyAgreementDeleteAPI" time="1.791" classname="com.arcapi.Common.VerifyAgreementDeleteAPITest">
    <failure type="java.lang.AssertionError" message="expected [403] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [403] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.VerifyAgreementDeleteAPITest.VerifyAgreementDeleteAPI(VerifyAgreementDeleteAPITest.java:29)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyAgreementDeleteAPI -->
  <testcase name="MetersAPI" time="1.989" classname="com.arcapi.Leedv4Testcases.MetersAPITest"/>
  <testcase name="HumanExperienceConsumptionCreateAPI" time="2.135" classname="com.arcapi.Leedv4Testcases.HumanExperienceConsumptionCreateAPITest">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;201&amp;gt; doesn&amp;apos;t match actual status code &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <201> doesn't match actual status code <404>.

	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
	at com.jayway.restassured.specification.ResponseSpecification$statusCode$1.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
	at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
	at com.arcapi.Leedv4Testcases.HumanExperienceConsumptionCreateAPITest.HumanExperienceConsumptionCreateAPI(HumanExperienceConsumptionCreateAPITest.java:30)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- HumanExperienceConsumptionCreateAPI -->
  <testcase name="HumanExperienceConsumptionUpdateAPI" time="2.097" classname="com.arcapi.Leedv4Testcases.HumanExperienceConsumptionUpdateAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.HumanExperienceConsumptionUpdateAPITest.HumanExperienceConsumptionUpdateAPI(HumanExperienceConsumptionUpdateAPITest.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- HumanExperienceConsumptionUpdateAPI -->
  <testcase name="VerifyManualConsumptionAfterUpdateAPI" time="1.794" classname="com.arcapi.Leedv4Testcases.VerifyManualConsumptionAfterUpdateAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.VerifyManualConsumptionAfterUpdateAPITest.VerifyManualConsumptionAfterUpdateAPI(VerifyManualConsumptionAfterUpdateAPITest.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyManualConsumptionAfterUpdateAPI -->
  <testcase name="HumanExperienceConsumptionDeleteAPI" time="2.082" classname="com.arcapi.Leedv4Testcases.HumanExperienceConsumptionDeleteAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.HumanExperienceConsumptionDeleteAPITest.HumanExperienceConsumptionDeleteAPI(HumanExperienceConsumptionDeleteAPITest.java:28)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- HumanExperienceConsumptionDeleteAPI -->
  <testcase name="VerifyManualConsumptionAPI" time="1.882" classname="com.arcapi.Leedv4Testcases.VerifyManualConsumptionAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.VerifyManualConsumptionAPITest.VerifyManualConsumptionAPI(VerifyManualConsumptionAPITest.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyManualConsumptionAPI -->
  <testcase name="HumanExperienceMeterUpdateAPI" time="2.073" classname="com.arcapi.Leedv4Testcases.HumanExperienceMeterUpdateAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.HumanExperienceMeterUpdateAPITest.HumanExperienceMeterUpdateAPI(HumanExperienceMeterUpdateAPITest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- HumanExperienceMeterUpdateAPI -->
  <testcase name="ExcelUploadTemplatePOSTAPI" time="3.663" classname="com.arcapi.Buildingtestcases.ExcelUploadTemplatePOSTAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Buildingtestcases.ExcelUploadTemplatePOSTAPITest.ExcelUploadTemplatePOSTAPI(ExcelUploadTemplatePOSTAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ExcelUploadTemplatePOSTAPI -->
  <testcase name="S3DocumentUploadPOSTAPI" time="2.894" classname="com.arcapi.Common.S3DocumentUploadPOSTAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.S3DocumentUploadPOSTAPITest.S3DocumentUploadPOSTAPI(S3DocumentUploadPOSTAPITest.java:32)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- S3DocumentUploadPOSTAPI -->
  <testcase name="S3DocumentListAPI" time="2.122" classname="com.arcapi.Common.S3DocumentListAPITest"/>
  <testcase name="S3DocumentRemoveAPI" time="1.923" classname="com.arcapi.Common.S3DocumentRemoveAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.S3DocumentRemoveAPITest.S3DocumentRemoveAPI(S3DocumentRemoveAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- S3DocumentRemoveAPI -->
  <testcase name="MeterCommentPostGroup1API" time="1.909" classname="com.arcapi.Leedv4Testcases.MeterCommentPostGroup1APITest">
    <failure type="java.lang.IllegalArgumentException" message="Cannot invoke method getAt() on null object">
      <![CDATA[java.lang.IllegalArgumentException: Cannot invoke method getAt() on null object
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:53)
	at com.jayway.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
	at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at com.jayway.restassured.path.json.JsonPath$get$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.path(RestAssuredResponseOptionsGroovyImpl.groovy:392)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.path(RestAssuredResponseOptionsImpl.java:195)
	at com.arcapi.Leedv4Testcases.MeterCommentPostGroup1APITest.MeterCommentPostGroup1API(MeterCommentPostGroup1APITest.java:33)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at Script1.run(Script1.groovy:1)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:591)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:629)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:600)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.jayway.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:76)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
	... 32 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- MeterCommentPostGroup1API -->
  <testcase name="MeterCommentPostGroup2API" time="302.018" classname="com.arcapi.Leedv4Testcases.MeterCommentPostGroup2APITest">
    <failure type="java.lang.IllegalArgumentException" message="Cannot invoke method getAt() on null object">
      <![CDATA[java.lang.IllegalArgumentException: Cannot invoke method getAt() on null object
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:53)
	at com.jayway.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
	at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at com.jayway.restassured.path.json.JsonPath$get$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.path(RestAssuredResponseOptionsGroovyImpl.groovy:392)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.path(RestAssuredResponseOptionsImpl.java:195)
	at com.arcapi.Leedv4Testcases.MeterCommentPostGroup2APITest.MeterCommentPostGroup2API(MeterCommentPostGroup2APITest.java:35)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at Script1.run(Script1.groovy:1)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:591)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:629)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:600)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.jayway.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:76)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
	... 32 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- MeterCommentPostGroup2API -->
  <testcase name="MeterCommentPostGroup3API" time="9.634" classname="com.arcapi.Leedv4Testcases.MeterCommentPostGroup3APITest"/>
  <testcase name="MeterCommentReplyGroup1API" time="1.878" classname="com.arcapi.Leedv4Testcases.MeterCommentReplyGroup1APITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.MeterCommentReplyGroup1APITest.MeterCommentReplyGroup1API(MeterCommentReplyGroup1APITest.java:38)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MeterCommentReplyGroup1API -->
  <testcase name="MeterCommentReplyGroup2API" time="301.916" classname="com.arcapi.Leedv4Testcases.MeterCommentReplyGroup2APITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.MeterCommentReplyGroup2APITest.MeterCommentReplyGroup2API(MeterCommentReplyGroup2APITest.java:39)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MeterCommentReplyGroup2API -->
  <testcase name="MeterCommentReplyGroup3API" time="5.755" classname="com.arcapi.Leedv4Testcases.MeterCommentReplyGroup3APITest"/>
  <testcase name="MeterCommentDeleteGroup2API" time="2.346" classname="com.arcapi.Leedv4Testcases.MeterCommentDeleteGroup2APITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.MeterCommentDeleteGroup2APITest.MeterCommentDeleteGroup2API(MeterCommentDeleteGroup2APITest.java:28)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MeterCommentDeleteGroup2API -->
  <testcase name="AssetTeamMemberRoleAPI" time="1.928" classname="com.arcapi.Common.AssetTeamMemberRoleAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetTeamMemberRoleAPITest.AssetTeamMemberRoleAPI(AssetTeamMemberRoleAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamMemberRoleAPI -->
  <testcase name="AssetTeamMemberListAPI" time="2.053" classname="com.arcapi.Common.AssetTeamMemberListAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetTeamMemberListAPITest.AssetTeamMemberListAPI(AssetTeamMemberListAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamMemberListAPI -->
  <testcase name="AssetTeamMemberAddPOSTAPI" time="1.987" classname="com.arcapi.Common.AssetTeamMemberAddPOSTAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetTeamMemberAddPOSTAPITest.AssetTeamMemberAddPOSTAPI(AssetTeamMemberAddPOSTAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamMemberAddPOSTAPI -->
  <testcase name="AssetTeamMemberUpdateAPI" time="2.007" classname="com.arcapi.Common.AssetTeamMemberUpdateAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetTeamMemberUpdateAPITest.AssetTeamMemberUpdateAPI(AssetTeamMemberUpdateAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamMemberUpdateAPI -->
  <testcase name="AssetTeamMemberRemoveAPI" time="1.868" classname="com.arcapi.Common.AssetTeamMemberRemoveAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetTeamMemberRemoveAPITest.AssetTeamMemberRemoveAPI(AssetTeamMemberRemoveAPITest.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamMemberRemoveAPI -->
  <testcase name="DeleteAllAppsAPI" time="2.013" classname="com.arcapi.Common.DeleteAllAppsAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.DeleteAllAppsAPITest.DeleteAllAppsAPI(DeleteAllAppsAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DeleteAllAppsAPI -->
  <testcase name="InstallAllAppsAfterDeleteAPI" time="1.979" classname="com.arcapi.Common.InstallAllAppsAfterDeleteAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.InstallAllAppsAfterDeleteAPITest.InstallAllAppsAfterDeleteAPI(InstallAllAppsAfterDeleteAPITest.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- InstallAllAppsAfterDeleteAPI -->
  <testcase name="AssetTeamPermissionListAPI" time="2.009" classname="com.arcapi.Common.AssetTeamPermissionListAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetTeamPermissionListAPITest.AssetTeamPermissionListAPI(AssetTeamPermissionListAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamPermissionListAPI -->
  <testcase name="AssetTeamPermissionPostAPI" time="1.809" classname="com.arcapi.Common.AssetTeamPermissionPostAPITest">
    <failure type="java.lang.AssertionError" message="expected [201] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetTeamPermissionPostAPITest.AssetTeamPermissionPostAPI(AssetTeamPermissionPostAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamPermissionPostAPI -->
  <testcase name="AssetTeamPermissionPutAPI" time="2.068" classname="com.arcapi.Common.AssetTeamPermissionPutAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetTeamPermissionPutAPITest.AssetTeamPermissionPutAPI(AssetTeamPermissionPutAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamPermissionPutAPI -->
  <testcase name="VerifyAdminRemoveAPI" time="1.762" classname="com.arcapi.Common.VerifyAdminRemoveAPITest">
    <failure type="java.lang.AssertionError" message="expected [403] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [403] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.VerifyAdminRemoveAPITest.VerifyAdminRemoveAPI(VerifyAdminRemoveAPITest.java:21)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyAdminRemoveAPI -->
  <testcase name="AssetTeamMemberAddPOSTAPI" time="1.912" classname="com.arcapi.Common.AssetArcProjectAdminAddPOSTAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetArcProjectAdminAddPOSTAPITest.AssetTeamMemberAddPOSTAPI(AssetArcProjectAdminAddPOSTAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetTeamMemberAddPOSTAPI -->
  <testcase name="AssetNotificationSubscriptionList" time="2.054" classname="com.arcapi.Common.AssetNotificationSubscriptionListTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetNotificationSubscriptionListTest.AssetNotificationSubscriptionList(AssetNotificationSubscriptionListTest.java:21)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetNotificationSubscriptionList -->
  <testcase name="AssetNotificationSubscriptionPost" time="1.997" classname="com.arcapi.Common.AssetNotificationSubscriptionPostTest"/>
  <testcase name="NotificationSubscriptionDetail" time="1.769" classname="com.arcapi.Common.NotificationSubscriptionDetailGetTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.NotificationSubscriptionDetailGetTest.NotificationSubscriptionDetail(NotificationSubscriptionDetailGetTest.java:21)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- NotificationSubscriptionDetail -->
  <testcase name="NotificationSubscriptionDetail" time="2.04" classname="com.arcapi.Common.NotificationSubscriptionDetailPutTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.NotificationSubscriptionDetailPutTest.NotificationSubscriptionDetail(NotificationSubscriptionDetailPutTest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- NotificationSubscriptionDetail -->
  <testcase name="NotificationSubscriptionDetailDelete" time="1.993" classname="com.arcapi.Common.NotificationSubscriptionDetailDeleteTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.NotificationSubscriptionDetailDeleteTest.NotificationSubscriptionDetailDelete(NotificationSubscriptionDetailDeleteTest.java:24)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- NotificationSubscriptionDetailDelete -->
  <testcase name="RecomputePerformanceScoreGet" time="2.086" classname="com.arcapi.Common.RecomputePerformanceScoreGetTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.RecomputePerformanceScoreGetTest.RecomputePerformanceScoreGet(RecomputePerformanceScoreGetTest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- RecomputePerformanceScoreGet -->
  <testcase name="NotificationCreatePOSTAPI" time="1.766" classname="com.arcapi.Common.NotificationCreatePOSTAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.NotificationCreatePOSTAPITest.NotificationCreatePOSTAPI(NotificationCreatePOSTAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- NotificationCreatePOSTAPI -->
  <testcase name="NotificationGetAPI" time="1.7" classname="com.arcapi.Common.NotificationGetAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.NotificationGetAPITest.NotificationGetAPI(NotificationGetAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- NotificationGetAPI -->
  <testcase name="NotificationDeleteAPI" time="2.361" classname="com.arcapi.Common.NotificationDeleteAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.NotificationDeleteAPITest.NotificationDeleteAPI(NotificationDeleteAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- NotificationDeleteAPI -->
  <testcase name="FeedbackSubmitPostAPI" time="1.721" classname="com.arcapi.Common.FeedbackSubmitPostAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.FeedbackSubmitPostAPITest.FeedbackSubmitPostAPI(FeedbackSubmitPostAPITest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- FeedbackSubmitPostAPI -->
  <testcase name="TransitSurveyExportAPI" time="2.068" classname="com.arcapi.Common.TransitSurveyExportAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.TransitSurveyExportAPITest.TransitSurveyExportAPI(TransitSurveyExportAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TransitSurveyExportAPI -->
  <testcase name="EnvironmentSurveyExportAPI" time="1.784" classname="com.arcapi.Common.EnvironmentSurveyExportAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.EnvironmentSurveyExportAPITest.EnvironmentSurveyExportAPI(EnvironmentSurveyExportAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- EnvironmentSurveyExportAPI -->
  <testcase name="AssetDataExportAPI" time="2.005" classname="com.arcapi.Common.AssetDataExportAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetDataExportAPITest.AssetDataExportAPI(AssetDataExportAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetDataExportAPI -->
  <testcase name="AssetPerformanceScoreListAPI" time="1.74" classname="com.arcapi.Common.AssetPerformanceScoreListAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AssetPerformanceScoreListAPITest.AssetPerformanceScoreListAPI(AssetPerformanceScoreListAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AssetPerformanceScoreListAPI -->
  <testcase name="AnalysisDataSubmitPOSTAPI" time="0.0" classname="com.arcapi.Common.AnalysisDataSubmitPOSTAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AnalysisDataSubmitPOSTAPITest.AnalysisDataSubmitPOSTAPI(AnalysisDataSubmitPOSTAPITest.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AnalysisDataSubmitPOSTAPI -->
  <testcase name="AnalysisDataGetAPI" time="2.043" classname="com.arcapi.Common.AnalysisDataGetAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Common.AnalysisDataGetAPITest.AnalysisDataGetAPI(AnalysisDataGetAPITest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- AnalysisDataGetAPI -->
  <testcase name="CO2GetTestAPI" time="1.908" classname="com.arcapi.Buildingtestcases.CO2GetTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Buildingtestcases.CO2GetTest.CO2GetTestAPI(CO2GetTest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- CO2GetTestAPI -->
  <testcase name="GhgGetTestAPI" time="2.118" classname="com.arcapi.Buildingtestcases.GhgGetTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Buildingtestcases.GhgGetTest.GhgGetTestAPI(GhgGetTest.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- GhgGetTestAPI -->
  <testcase name="GhgCalcGet" time="1.806" classname="com.arcapi.Buildingtestcases.GhgCalcGetTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Buildingtestcases.GhgCalcGetTest.GhgCalcGet(GhgCalcGetTest.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- GhgCalcGet -->
  <testcase name="VOCGet" time="1.801" classname="com.arcapi.Buildingtestcases.VOCGetTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Buildingtestcases.VOCGetTest.VOCGet(VOCGetTest.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VOCGet -->
  <testcase name="WaterGet" time="1.895" classname="com.arcapi.Buildingtestcases.WaterGetTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Buildingtestcases.WaterGetTest.WaterGet(WaterGetTest.java:20)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- WaterGet -->
  <testcase name="ExcelTemplateMetersAPI" time="2.082" classname="com.arcapi.Buildingtestcases.ExcelTemplateMetersAPITest">
    <failure type="java.lang.IllegalArgumentException" message="Cannot get property &amp;apos;id&amp;apos; on null object">
      <![CDATA[java.lang.IllegalArgumentException: Cannot get property 'id' on null object
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:53)
	at com.jayway.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
	at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at com.jayway.restassured.path.json.JsonPath$get$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.path(RestAssuredResponseOptionsGroovyImpl.groovy:392)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.path(RestAssuredResponseOptionsImpl.java:195)
	at com.arcapi.Buildingtestcases.ExcelTemplateMetersAPITest.ExcelTemplateMetersAPI(ExcelTemplateMetersAPITest.java:25)
Caused by: java.lang.NullPointerException: Cannot get property 'id' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at Script1.run(Script1.groovy:1)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:591)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:629)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:600)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.jayway.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:76)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
	... 32 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- ExcelTemplateMetersAPI -->
  <testcase name="VerifyExcelTemplateConsumptionAPI" time="1.846" classname="com.arcapi.Buildingtestcases.VerifyExcelTemplateConsumptionAPITest">
    <failure type="java.lang.IllegalArgumentException" message="Cannot get property &amp;apos;reading&amp;apos; on null object">
      <![CDATA[java.lang.IllegalArgumentException: Cannot get property 'reading' on null object
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:53)
	at com.jayway.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
	at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at com.jayway.restassured.path.json.JsonPath$get$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.path(RestAssuredResponseOptionsGroovyImpl.groovy:392)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.path(RestAssuredResponseOptionsImpl.java:195)
	at com.arcapi.Buildingtestcases.VerifyExcelTemplateConsumptionAPITest.VerifyExcelTemplateConsumptionAPI(VerifyExcelTemplateConsumptionAPITest.java:52)
Caused by: java.lang.NullPointerException: Cannot get property 'reading' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at Script1.run(Script1.groovy:1)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:591)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:629)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:600)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.jayway.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:76)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
	... 32 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- VerifyExcelTemplateConsumptionAPI -->
  <testcase name="VerifyWasteDataExcelAPI" time="2.305" classname="com.arcapi.Buildingtestcases.VerifyWasteDataExcelAPITest">
    <failure type="java.lang.IllegalArgumentException" message="Cannot get property &amp;apos;waste_generated&amp;apos; on null object">
      <![CDATA[java.lang.IllegalArgumentException: Cannot get property 'waste_generated' on null object
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:53)
	at com.jayway.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:28)
	at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at com.jayway.restassured.path.json.JsonPath$get$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.path(RestAssuredResponseOptionsGroovyImpl.groovy:392)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.path(RestAssuredResponseOptionsImpl.java:195)
	at com.arcapi.Buildingtestcases.VerifyWasteDataExcelAPITest.VerifyWasteDataExcelAPI(VerifyWasteDataExcelAPITest.java:25)
Caused by: java.lang.NullPointerException: Cannot get property 'waste_generated' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at Script1.run(Script1.groovy:1)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:591)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:629)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:600)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.jayway.restassured.internal.path.json.JSONAssertion.eval(JSONAssertion.groovy:76)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:46)
	... 32 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- VerifyWasteDataExcelAPI -->
  <testcase name="VerifyActivityEnergyDataInputAPI" time="1.675" classname="com.arcapi.Leedv4Testcases.VerifyActivityEnergyDataInputAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.VerifyActivityEnergyDataInputAPITest.VerifyActivityEnergyDataInputAPI(VerifyActivityEnergyDataInputAPITest.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyActivityEnergyDataInputAPI -->
  <testcase name="VerifyActivityWaterDataInputAPI" time="1.943" classname="com.arcapi.Leedv4Testcases.VerifyActivityWaterDataInputAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.VerifyActivityWaterDataInputAPITest.VerifyActivityWaterDataInputAPI(VerifyActivityWaterDataInputAPITest.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyActivityWaterDataInputAPI -->
  <testcase name="VerifyActivityWasteDataInputAPI" time="1.782" classname="com.arcapi.Leedv4Testcases.VerifyActivityWasteDataInputAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.VerifyActivityWasteDataInputAPITest.VerifyActivityWasteDataInputAPI(VerifyActivityWasteDataInputAPITest.java:24)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyActivityWasteDataInputAPI -->
  <testcase name="VerifyActivityHEMeterDataInputAPI" time="1.843" classname="com.arcapi.Leedv4Testcases.VerifyActivityHEMeterDataInputAPITest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
	at com.Utill.Controller.Assertion.verifyStatusCode(Assertion.java:20)
	at com.arcapi.Leedv4Testcases.VerifyActivityHEMeterDataInputAPITest.VerifyActivityHEMeterDataInputAPI(VerifyActivityHEMeterDataInputAPITest.java:26)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyActivityHEMeterDataInputAPI -->
</testsuite> <!-- LEED v4.1 O+M: Existing Buildings -->
