<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="G10GGNLT052" name="com.arcapi.Common.V2.VerifyBasicAnalysisDataGetAPITest" tests="1" failures="1" timestamp="10 Oct 2019 08:21:47 GMT" time="2.150" errors="0">
  <testcase name="VerifyBasicAnalysisDataGetAPI" time="2.150" classname="com.arcapi.Common.V2.VerifyBasicAnalysisDataGetAPITest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [206] but found [50],
	expected [3000.0] but found [1000.0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [206] but found [50],
	expected [3000.0] but found [1000.0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.arcapi.Common.V2.VerifyBasicAnalysisDataGetAPITest.VerifyBasicAnalysisDataGetAPI(VerifyBasicAnalysisDataGetAPITest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- VerifyBasicAnalysisDataGetAPI -->
</testsuite> <!-- com.arcapi.Common.V2.VerifyBasicAnalysisDataGetAPITest -->
