<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="G10GGNLT052" name="com.arcapi.ScenarioBasedTestcases.VerifyGeneralVisitorOccupantDatacoverageAPITest" tests="1" failures="1" timestamp="7 Nov 2019 09:54:02 GMT" time="1.560" errors="0">
  <testcase name="VerifyGeneralVisitorOccupantDatacoverageAPI" time="1.560" classname="com.arcapi.ScenarioBasedTestcases.VerifyGeneralVisitorOccupantDatacoverageAPITest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [50.0] but found [25.0],
	expected [50.0] but found [{coverage_flag=green, percentage=75.0}]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [50.0] but found [25.0],
	expected [50.0] but found [{coverage_flag=green, percentage=75.0}]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.arcapi.ScenarioBasedTestcases.VerifyGeneralVisitorOccupantDatacoverageAPITest.VerifyGeneralVisitorOccupantDatacoverageAPI(VerifyGeneralVisitorOccupantDatacoverageAPITest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- VerifyGeneralVisitorOccupantDatacoverageAPI -->
</testsuite> <!-- com.arcapi.ScenarioBasedTestcases.VerifyGeneralVisitorOccupantDatacoverageAPITest -->
